### ISSUE TITLE
Conversion of simplification script to C++

### ISSUE THREAD

**Issue by waseemkhan1989** [HusseinBakri/3DMeshBulkSimplification#2]
Hi,

I want to convert this 3DMeshBulkSimplification scripts(particularly simplify.py) to C++ because the software into which I want to integrate this simplification feature is written in C++. Any thing that I should keep in mind while converting to C++?

Thanks.
Regards,
Waseem Khan

**Comment by HusseinBakri** [comment]
Sorry I can not help you out. Have a look for what is available stackoverflow or contact the folks of Meshlab they might be able to point you in the right direction
